#include "BLG/src/generator/dec_generator.hpp"
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

// Function to write the config code header
inline void write_config_code_header(int N, int GF) {
  // Target file path
  std::string target_file = "../src/definitions/code.hpp";

  // Determine which code file to include based on N and GF
  std::ostringstream include_file;
  include_file << "codes/N" << N << "_GF" << GF << ".hpp";

  std::cout << "📝 Writing config header to: " << target_file << std::endl;
  std::cout << "   Including: " << include_file.str() << std::endl;

  // Open the file for writing
  std::ofstream outfile(target_file);
  if (!outfile) {
    std::cerr << "❌ Cannot open config header file for writing: "
              << target_file << std::endl;
    std::exit(EXIT_FAILURE);
  }

  // Write the header content
  outfile << "#ifndef CONFIG_CODE_H\n";
  outfile << "#define CONFIG_CODE_H\n";
  outfile << "\n";
  outfile << "// Auto-generated by call_dec_generator\n";
  outfile << "// Configuration for N=" << N << ", GF=" << GF << "\n";
  outfile << "// Generated on: " << __DATE__ << " " << __TIME__ << "\n";
  outfile << "\n";
  outfile << "#include \"" << include_file.str() << "\"\n";
  outfile << "\n";
  outfile << "#endif // CONFIG_CODE_H\n";

  outfile.close();

  if (outfile.good()) {
    std::cout << "✅ Successfully wrote config header" << std::endl;
  } else {
    std::cerr << "❌ Error writing config header" << std::endl;
    std::exit(EXIT_FAILURE);
  }
}

// Load reliability sequence (method selectable)
// method = 1 → first sequence
// method = 2 → second sequence
inline std::vector<uint16_t> load_reliability_sequence(int GF, int N,
                                                       float SNR) {
  // Determine the base path relative to the current working directory
  std::string base_dir = "../matrices/";

  // Build the folder path: ./BLG/matrices/GF64/
  std::ostringstream folder;
  folder << base_dir << "GF" << GF << "/";

  // Build the file path: ./BLG/matrices/GF64/GF64N64.txt
  std::ostringstream fname;
  fname << folder.str() << "GF" << GF << "N" << N << ".txt";

  std::string filename = fname.str();
  std::cout << "Reading reliability file: " << filename << std::endl;

  std::ifstream file(filename);
  if (!file) {
    std::cerr << "❌ Cannot open reliability file: " << filename << std::endl;
    std::exit(EXIT_FAILURE);
  }

  // --- Read SNR + sequence blocks (Matching the LoadCode structure) ---
  struct entry_t {
    float snr;
    std::vector<uint16_t> seq;
  };
  std::vector<entry_t> entries;

  while (true) {
    std::string tag;
    float snr_val;

    // Try to read "SNR" tag and the float value
    if (!(file >> tag >> snr_val))
      break; // End of file or read error

    if (tag != "SNR") {
      std::cerr << "❌ Invalid format: expected 'SNR' tag in file: " << filename
                << std::endl;
      std::exit(EXIT_FAILURE);
    }

    // Read reliability sequence (N integers)
    std::vector<uint16_t> seq(N);
    for (int i = 0; i < N; i++) {
      int t;
      if (!(file >> t)) {
        std::cerr << "❌ Missing sequence entry at index " << i << " for SNR "
                  << snr_val << std::endl;
        std::exit(EXIT_FAILURE);
      }
      seq[i] = static_cast<uint16_t>(t);
    }

    entries.push_back({snr_val, seq});
  }

  if (entries.empty()) {
    std::cerr << "❌ No SNR entries found in file: " << filename << std::endl;
    std::exit(EXIT_FAILURE);
  }

  // --- Find nearest SNR to the requested SNR ---
  float best_dist = 1000.0f; // Use a large number instead of hard-coded 2
  int best_idx = -1;

  for (int i = 0; i < (int)entries.size(); i++) {
    float d = std::abs(entries[i].snr - SNR);
    if (d < best_dist) {
      best_dist = d;
      best_idx = i;
    }
  }

  if (best_idx < 0) {
    std::cerr << "❌ Nearest SNR not found!" << std::endl;
    std::exit(EXIT_FAILURE);
  }

  // --- Output and Return ---
  std::cout << "✅ Requested SNR: " << SNR
            << " --> Using nearest SNR: " << entries[best_idx].snr << " from "
            << filename << std::endl;

  return entries[best_idx].seq;
}

int main(int argc, char *argv[]) {
  if (argc < 5) {
    std::cerr << "Usage: " << argv[0] << " <N> <K> <GF> <SNR>\n";
    std::cerr << "Example: " << argv[0] << " 64 42 64 1.0\n";
    return 1;
  }

  const int N = std::atoi(argv[1]);
  const int K = std::atoi(argv[2]);
  const int GF = std::atoi(argv[3]);
  const float SNR = std::atof(argv[4]);

  std::cout << "Running decoder generator with:\n"
            << "  N   = " << N << "\n"
            << "  K   = " << K << "\n"
            << "  GF  = " << GF << "\n"
            << "  SNR = " << SNR << "\n";

  // Write the config header first
  write_config_code_header(N, GF);

  std::vector<uint16_t> reliab_sequence = load_reliability_sequence(GF, N, SNR);

  std::vector<int> frozen(N, 1); // all frozen initially
  for (int i = 0; i < K && i < (int)reliab_sequence.size(); i++)
    frozen[reliab_sequence[i]] = 0;

  dec_generator gen(N, GF);
  gen.verbose = true;
  gen.analyze(frozen.data(), N);

  return 0;
}