
#include "Decoder_functions.h"
#include "struct.h"
#include "definitions/code.hpp"
#include "ccsk_simulator/ccsk_llr.hpp"
#include <cmath>
#include <memory>
#include <mutex>
#include <stdexcept>
#include <vector>

namespace
{
void llr_to_probabilities(const std::vector<double> &llr,
                              const int q,
                              std::vector<PoAwN::structures::softdata_t> &probabilities)
{
    double sum = 0.0;
    for (int j = 0; j < q; ++j)
    {
        probabilities[j] = static_cast<PoAwN::structures::softdata_t>(std::exp(-llr[j]));
        sum += probabilities[j];
    }
    for (int j = 0; j < q; ++j)
    {
        probabilities[j] = static_cast<PoAwN::structures::softdata_t>(probabilities[j] / sum);
    }
}
} // namespace

void PoAwN::decoding::Channel_LLR(const vector<vector<softdata_t>> &chan_observ,
                                  uint16_t q,
                                  softdata_t sigma,
                                  vector<vector<softdata_t>> &chan_LLR)
{
    const int N = chan_observ.size();
    const int q1 = chan_observ[0].size();

    if (q != q1 || q1 <= 0 || ((q1 & (q1 - 1)) != 0))
    {
        throw std::runtime_error("FFTW CCSK LLR requires q == chips_per_symbol and a power-of-two length");
    }
    if (q != _GF_)
    {
        throw std::runtime_error("FFTW CCSK LLR uses the compile-time GF generated by CMake");
    }

    static std::mutex llr_mutex;
    static softdata_t cached_sigma = 0;
    static std::unique_ptr<CCSK_LLR<_GF_>> llr_calculator;

    {
        std::lock_guard<std::mutex> lock(llr_mutex);
        if (!llr_calculator || cached_sigma != sigma)
        {
            llr_calculator = std::make_unique<CCSK_LLR<_GF_>>(static_cast<double>(sigma));
            cached_sigma = sigma;
        }
    }
    CCSK_LLR<_GF_> *calculator = llr_calculator.get();

    std::vector<double> observation(q1);
    std::vector<double> llr(q);
    for (int i = 0; i < N; i++)
    {
        for (int k = 0; k < q1; ++k)
        {
            observation[k] = static_cast<double>(chan_observ[i][k]);
        }
        calculator->calculate(observation.data(), llr.data());
        llr_to_probabilities(llr, q, chan_LLR[i]);
    }
}
